name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Autenticação do usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
    
      - name: Contruindo a imagem e enviando para o Docker Hub (Build and push Docker images)
        uses: docker/build-push-action@v3.1.0
        with:
            file: ./src/Dockerfile
            context: ./src
            push: true
            tags: |
              msantinello/kube-news:latest
              msantinello/kube-news:${{github.run_number}}
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - uses: actions/checkout@v3
      - name: Definindo o kubeconfig (Kubernetes Set Context)
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
      - name: Efetudando o deploy no kubernetes (Deploy to Kubernetes cluster)
        uses: Azure/k8s-deploy@v4.3
        with:
          images: msantinello/kube-news:${{github.run_number}}
          manifests: k8s/deployment.yaml
